### ISSUE TITLE
data

### ISSUE THREAD

**Issue by JiunShiang880109** [cscribano/AYCE_2021#1]
could you provide your datapackeg?
I can't download this data on this Official website.
Because if want download this data should though the passward to download, and i haven't passward to download this data.

**Comment by cscribano** [comment]
The dataset is provided by the organizers of the AI City Challenge, distributing it not allowed.
I'm sorry I can't help you.

**Comment by JiunShiang880109** [comment]
> 數據集由AI城市挑戰賽主辦方提供，禁止傳播。 對不起，我幫不了你。

ok thanks for your reply
